name: Visaku

options:
  bundleIdPrefix: com.insiders.visaku
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 17.0

packages:
  UIComponentModule:
    url: https://github.com/InsidersID/UIComponentModule.git
    branch: main
  RepositoryModule:
    url: https://github.com/InsidersID/RepositoryModule.git
    branch: main
  RiveRuntime:
    url: https://github.com/rive-app/rive-ios
    from: '6.3.3'

targetTemplates:
  Module:
    type: framework
    platform: iOS
    deploymentTarget: 17.0
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MACCATALYST: false

targets:
  Visaku:
    type: application
    platform: iOS
    sources: [Visaku, Visaku/Assets.xcassets]

    info:
      path: Visaku/Info.plist
      properties:
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleDisplayName: "Visaku"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "APPL"
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSCameraUsageDescription: "Fitur kamera digunakan untuk mengambil dan memproses dokumenmu. Tenang saja, gambar dokumenmu tidak akan dikirim keluar dari perangkatmu."
        UIAppFonts:
          - Inter-Black.ttf
          - Inter-BlackItalic.ttf
          - Inter-Bold.ttf
          - Inter-BoldItalic.ttf
          - Inter-ExtraBold.ttf
          - Inter-ExtraBoldItalic.ttf
          - Inter-ExtraLight.ttf
          - Inter-ExtraLightItalic.ttf
          - Inter-Italic.ttf
          - Inter-Light.ttf
          - Inter-LightItalic.ttf
          - Inter-Medium.ttf
          - Inter-MediumItalic.ttf
          - Inter-Regular.ttf
          - Inter-SemiBold.ttf
          - Inter-SemiBoldItalic.ttf
          - Inter-Thin.ttf
          - Inter-ThinItalic.ttf
          - Poppins-Black.ttf
          - Poppins-BlackItalic.ttf
          - Poppins-Bold.ttf
          - Poppins-BoldItalic.ttf
          - Poppins-ExtraBold.ttf
          - Poppins-ExtraBoldItalic.ttf
          - Poppins-ExtraLight.ttf
          - Poppins-ExtraLightItalic.ttf
          - Poppins-Italic.ttf
          - Poppins-Light.ttf
          - Poppins-LightItalic.ttf
          - Poppins-Medium.ttf
          - Poppins-MediumItalic.ttf
          - Poppins-Regular.ttf
          - Poppins-SemiBold.ttf
          - Poppins-SemiBoldItalic.ttf
          - Poppins-Thin.ttf
          - Poppins-ThinItalic.ttf
        UILaunchStoryboardName: 'LaunchScreen'
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: 'com.insiders.visaku'
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: UIComponentModule
      - package: RepositoryModule
      - package: RiveRuntime

  VisakuTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: VisakuTests
    dependencies:
      - target: Visaku
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: 'com.insiders.visaku.tests'

  VisakuUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: VisakuUITests
    dependencies:
      - target: Visaku
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: 'com.insiders.visaku.uitests'
