name: Visaku

options:
  bundleIdPrefix: com.insiders.visaku
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 17.0

packages:
  UIComponentModule:
    url: https://github.com/InsidersID/UIComponentModule.git
    branch: main
  RepositoryModule:
    url: https://github.com/InsidersID/RepositoryModule.git
    branch: main
  Rive:
    url: https://github.com/rive-app/rive-ios
    from: '6.3.3'

targetTemplates:
  Module:
    type: framework
    platform: iOS
    deploymentTarget: 17.0
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MACCATALYST: false

targets:
  Visaku:
    type: application
    platform: iOS
    sources: [Visaku, Visaku/Assets.xcassets]

    info:
      path: Visaku/Info.plist
      properties:
        UILaunchStoryboardName: 'LaunchScreen'
        CFBundleDisplayName: 'Test'
        CFBundleShortVersionString: '1.0.0'
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: 'com.insiders.visaku'
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: UIComponentModule
      - package: RepositoryModule
      - package: RiveRuntime

  VisakuTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: VisakuTests
    dependencies:
      - target: Visaku
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: 'com.insiders.visaku.tests'

  VisakuUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: VisakuUITests
    dependencies:
      - target: Visaku
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: 'com.insiders.visaku.uitests'
